let Carreras = [
    "Ingeniería de Software",
    "Ingeniería Informática",
    "Licenciatura en Sistemas de Información",
    "Licenciatura en Seguridad Informática",
    "Ingeniería en Redes y Telecomunicaciones",
    "Licenciatura en Inteligencia Artificial",
    "Ingeniería de Datos",
    "Licenciatura en Ciencias de la Salud",
    "Doctorado en Medicina",
    "Licenciatura en Odontología",
    "Licenciatura en Medicina Veterinaria",
    "Licenciatura en Farmacia",
    "Licenciatura en Nutrición",
    "Licenciatura en Matemáticas",
    "Licenciatura en Física",
    "Licenciatura en Química",
    "Licenciatura en Psicología",
    "Licenciatura en Arquitectura",
    "Licenciatura en Psicología",
    "Licenciatura en Administración de Empresas",
    "Licenciatura en Diseño Gráfico",
    "Licenciatura en Marketing Digital",
    "Licenciatura en Ciencias de la Computación",
    "Licenciatura en Educación",
    "Licenciatura en Enfermería",
    "Licenciatura en Contabilidad",
    "Licenciatura en Comunicación Social",
    "Licenciatura en Biología",
    "Licenciatura en Economía",
    "Licenciatura en Turismo",
    "Ingeniería Civil",
    "Licenciatura en Periodismo",
    "Licenciatura en Relaciones Internacionales",
    "Licenciatura en Filosofía",
    "Licenciatura en Derecho y Ciencias Políticas",
    "Ingeniería Industrial",
    "Ingeniería de Sistemas",
    "Licenciatura en Historia",
    "Licenciatura en Literatura",
    "Licenciatura en Filosofía",
    "Licenciatura en Sociología"
]