let idiomas = [
    "Inglés",
    "Español",
    "Francés",
    "Alemán",
    "Chino Mandarín",
    "Japonés",
    "Italiano",
    "Portugués",
    "Ruso",
    "Árabe",
    "Holandés",
    "Sueco",
    "Coreano",
    "Hindi",
    "Turco",
    "Griego",
    "Hebreo",
    "Polaco",
    "Danés",
    "Noruego",
    "Finlandés",
    "Checo",
]